database:
  username: ${username.value:postgres}
  password: 123
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
  properties:
    first: 123
    second: 567
    third.value: Third

spring.profiles.active: qa

# Тут мы указываем уровни логирования. ПО умолчанию мы задали уровень WARN, но для класса ConnectionPool мы поставили INFO. В результате
# мы будем видеть все сообщения WARN и сообщения INFO из класса ConnectionPool. Также можно задать и для пакета целиком.
logging:
  level:
    root: WARN
    com.spring.database.pool.ConnectionPool: INFO
