server:
  port: 8585

database:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
  properties:
    first: 123
    second: 567
    third.value: Third

spring.profiles.active: qa

# Тут мы передаем настройки для работы с базой данных и mvc
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#    format:
#      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false


# Тут мы указываем уровни логирования. ПО умолчанию мы задали уровень WARN, но для класса ConnectionPool мы поставили INFO. В результате
# мы будем видеть все сообщения WARN и сообщения INFO из класса ConnectionPool. Также можно задать и для пакета целиком.
# С помощью атрибута file мы сохраняем логи в файл с названием testLog.log (может быть любым), который будет в данном случае лежать рутовой
# директории проекта
# Если в поле root указать OFF, то ни один уровень логирования не будет отражен.
logging:
  level:
    root: INFO
    com.spring.database.pool.ConnectionPool: INFO
    org.springframework.jdbc.core: TRACE
  file:
    name: testLog.log
    path: /
